### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by bettinaheim**
Fixes the typos pointed out in #5.

### CODE REVIEW

**Review by amccaskey — APPROVED** [review]
Everything looks good here to me. All typos have been addressed.

**Comment by LaurentAjdnik** [comment]
Hi @bettinaheim and @amccaskey!

My issue (#5) also suggested we should replace occurrences of can't/don't/doesn't by cannot/do not/does not.

This would look more formal, which could be a good thing for a specification. 😁

What do you think?

**Review by kalzoo — APPROVED** [review]
Looks good to me, thanks @bettinaheim . I do appreciate the feedback and close eye from @LaurentAjdnik , but I'm happy to leave the contractions alone unless they cause a practical issue.

**Comment by bettinaheim** [comment]
Thanks, @LaurentAjdnik and @kalzoo!
I also did the suggested replacement of can't, don't and doesn't.

**Pull request merged**
